[build]
    publish = "_dist"

[context.production]
    [context.production.environment]
        DEV = "false"
        DEMOC_HASH = "0xcd563f0a5f1cd31f3d0798e3d33ed191095c60dac0bcbda220571184af013c71"
        INDEX_ADDR = "0xa8a8509A17a5872d01e489fC85B152eb2A0C092E"
        DELEGATION_ADDR = "0xf71ea2028e3c3fa58df8922eae6f5482123a17d4"
        YARN_VERSION = "0.18.1"

[context.deploy-preview.environment]
    DEV = "false"
    DEMOC_HASH = "0xcd563f0a5f1cd31f3d0798e3d33ed191095c60dac0bcbda220571184af013c71"
    INDEX_ADDR = "0xa8a8509A17a5872d01e489fC85B152eb2A0C092E"
    DELEGATION_ADDR = "0xf71ea2028e3c3fa58df8922eae6f5482123a17d4"
    YARN_VERSION = "0.18.1"

[context.branch-deploy.environment]
    DEV = "true"
    DEMOC_HASH = "0x8ac71cdcdb1d13afaa7aa82799d816e3d8b9fc20025f4a5af906a72f21bcc78e"
    INDEX_ADDR = "0x472420d75CE7f13a629770ebdC999e35e4f5142e"
    DELEGATION_ADDR = "0x8F6F18b9A83E0b42cE69783a8282441BF8F417fc"
    YARN_VERSION = "0.18.1"
